### ISSUE TITLE
Feature request: Add Flatpak,snap & Appimage package

### ISSUE THREAD

**Issue by dtantono** [kerrongordon/whatsapp-linux#59]
it would be great if we could have at hand this app in a Flatpak,snap & appimage format.

**Comment by kerrongordon** [comment]
For now we offer Appimage, deb and rpm which can be [downloaded from here](https://github.com/kerrongordon/whatsapp-linux/releases/latest)

**Comment by kerrongordon** [comment]
A snap package is now available for [download](https://snapcraft.io/whatsapplinux)
